# Generated by Django 4.2.7 on 2026-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientdoctormapping',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='patientdoctormapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient', 'doctor'), name='unique_active_patient_doctor'),
        ),
    ]
